# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hubot_notify"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Sutcliffe", "Brian Harrington"]
  s.date = "2013-12-06"
  s.description = "This plugin for Foreman uses the native httpd-post-say plugin provided by hubot."
  s.email = "redbeard@redhat.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "app/controllers/hubot_notify/unattended_controller_extensions.rb",
    "lib/hubot_notify.rb",
    "lib/hubot_notify/engine.rb"
  ]
  s.homepage = "http://github.com/brianredbeard/hubot_notify"
  s.licenses = ["GPL-3"]
  s.require_paths = ["lib", "app"]
  s.rubygems_version = "1.8.24"
  s.summary = "A plugin to send Foreman notifications to hubot"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

